### PR TITLE
Add style

### LINKED ISSUE #2: 7. Add style
### Repo

- [ ] developed on a branch named `style`
- [ ] Edit `style.css`

### PR DESCRIPTION
**Pull request by aleks2407**
Closes gh-2

### CODE REVIEW

**Review by Feruzteame — APPROVED** [review]

**Comment by Feruzteame** [comment]
For me it looks nice !

**Comment by aleks2407** [comment]
Thank you @Feruzteame :-)

**Review by yildiraykoyuncu — APPROVED** [review]
very nice

**Review by razvanbrb — COMMENTED** [review]
Great job!

**Review by razvanbrb — APPROVED** [review]

**Review by abelRoland — APPROVED** [review]
Great job!

**Pull request merged**
