### PR TITLE
fixed remove-number.js

### LINKED ISSUE #11: remove-numbers
## 6. Fix `remove-numbers.js`

__As a site visitor, I want to execute the function `remove-numbers.

### Repo

- [ ] developed on a branch named `remove-numbers`
- [ ] finish the function `remove-numbers.js`

### PR DESCRIPTION
**Pull request by yildiraykoyuncu**
wrote the logic for `removeNumber()`
fixed `removeNumberHandler()`
 
close #11

### CODE REVIEW

**Review by abelRoland — APPROVED** [review]
Thanks for the work.
I just notice that there is no specific logic / message to handle numbers that the user inserts and that are not present on the array, but I think that this is not a problem. Thanks again.

**Comment by aleks2407** [comment]
I think, the idea was to create a new Array, not modifying the old one. In this case if I'm not mistaken, you are changing the existing one, right? @yildiraykoyuncu @abelRoland

**Comment by yildiraykoyuncu** [comment]
Not exactly. Actually removeNumber() returns a new array. Because it`s what .filter() method does. But when we call the removeNumberHandler() it assigns the return value of  removeNumber() to "numbers" array. Practically we are changing `numbers` array with a new one we are not mutating it. I wrote it that way because every time we call a handler function it calls displayArrayHandler() at the end, and it displays the final status of `numbers` array so we can see the numbers we add or we remove. So I thought that we should be adding an removing numbers to "numbers" array. We can declare a new array every time we call the handler and assign the return value removeNumber to that new array and display it. It can work that way too. I can change it if you like. We can lost the track of arrays. I mean when we call addNumber() it will return a new array, "numbers" array will stay the same. Then when you want to remove a number, the function will get "numbers" array and remove a number from it and return a new array but you won`t be able to remove a number you add before because `numbers` array always stays the same it won`t be updated.

**Comment by aleks2407** [comment]
Ah no! this way is good for me!Thanks for detailed explanation @yildiraykoyuncu ! JS is not easy for me, so it is nice to learn from each other! well done)

**Review by aleks2407 — APPROVED** [review]

**Comment by yildiraykoyuncu** [comment]
You are welcome!! 👍 😄

**Pull request merged**
