### PR TITLE
REAdME.md

### LINKED ISSUE #4: Feruz : Add readme.md
# Add readme.md
> As a repo visitor, I want to know about the repository and the team

* assigned to Feruz

> Repo
- [x] developed on a branch named readme
- [x] Edit readme.md

### LINKED ISSUE #17: README.md photo
Screenshot 2020-07-10 at 12 01 59

### PR DESCRIPTION
**Pull request by Feruzteame**
close #4 
closes #17 
This is the introduction of our project in README.md. if you want to add something just tell me. After merge the style i will take screenshot and put in the last part of the README.md.

### CODE REVIEW

**Review by abelRoland — CHANGES_REQUESTED** [review]
Thanks for the work @Feruzteame . I saw that you were waiting for the pull request of the style to place it on this file, now I already merged, so you can add the print screen now before we make the final merge of readme file to master. Greetings

**Review by razvanbrb — APPROVED** [review]

**Review by yildiraykoyuncu — APPROVED** [review]

**Review by aleks2407 — APPROVED** [review]
Thanks @Feruzteame!  well done!

**Review by abelRoland — APPROVED** [review]
Perfect. Thanks!

**Comment by Feruzteame** [comment]
@abelRoland  i already upload the photo.
and you have a change request but i can not see where you need the change.

**Comment by abelRoland** [comment]
Hey @Feruzteame , yes I just told about the photo. Now that you already upload it I already review again, approve and merge. Thanks!

**Comment by Feruzteame** [comment]
Ahh  No problem ! Thanks

**Pull request merged**
