### PR TITLE
Done

### LINKED ISSUE #3: Feruz : display-array.js
# Fix display-array.js

> As a site visitor, I want to execute the function display-array.js

* assigned to Feruz

> Repo

- [x] developed on a branch named display-array
- [x] finish the function display-array.js

### PR DESCRIPTION
**Pull request by Feruzteame**
closes #3 
I try to do the display part, but i not sure our website will work with alert or with display in the page. I do both when we decide
i can remove one of it.

### CODE REVIEW

**Review by aleks2407 — APPROVED** [review]

**Review by abelRoland — APPROVED** [review]
Thanks @Feruzteame . For me I like the display on the page, I just am not sure about we using since in theory we still didn't study DOM manipulation. But, just to put my opinion, for me is ok 😄 .

**Comment by Feruzteame** [comment]
Thank you ! @abelRoland .

**Review by abelRoland — APPROVED** [review]
Nice. Good job!

**Review by razvanbrb — APPROVED** [review]
Great job!

**Pull request merged**
